### ISSUE TITLE
TypeError: sequence index must be integer, not 'str'

### ISSUE THREAD

**Issue by Kareeeeem** [authlib/example-oauth2-server#24]
There is another issue but it is closed. This is my first time reporting something so I'm not sure if leaving a comment on a closed issue actually does something. 

Anyways I'm stilll having the same problem. The other issue mentions using oauthlib 0.6.0 but no succes. Any ideas?

https://github.com/lepture/example-oauth2-server/issues/4

**Comment by lepture** [comment]
Delete all cookies. Use the latest Flask-OAuthlib. Try to print the response and give me more information.

**Comment by Kareeeeem** [comment]
Here is a screenshot of my terminal output and the debugger. In the debugger I ran `print resp`

![screenshot 2015-03-27 at 12 16 49](https://cloud.githubusercontent.com/assets/2920965/6866788/0dfbc27a-d47c-11e4-8f25-78131224307b.png)

and this is the output of `pip freeze`

```
Flask==0.10.1
# latest version of flask-oauthlib from github
-e git+git@github.com:lepture/flask-oauthlib.git@64d82c7d1fc9118c904940b0c5aa49cb5180a277#egg=Flask_OAuthlib-master
Flask-SQLAlchemy==2.0
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
oauthlib==0.7.2
requests==2.6.0
requests-oauthlib==0.4.2
SQLAlchemy==0.9.9
Werkzeug==0.10.4
```

**Comment by Kareeeeem** [comment]
Any ideas?

**Comment by spicyramen** [comment]
Same issue here

**Comment by benfa94** [comment]
same issue

**Comment by ashish-arora02** [comment]
Same issue , Any updates on this?

**Comment by ashish-arora02** [comment]
I have found this issue, it is due to the "Post" method not allowed to access_token function in app.py file. It is working at my end now. Here is the code diff https://github.com/ashish-arora02/example-oauth2-server/commit/5f8658e1316c9d615994629d525cf5e87f48b9ab

**Comment by lepture** [comment]
Fixed by https://github.com/lepture/example-oauth2-server/commit/e647be2c185be5e1318beee3be43c6ae250f6fb5

**Comment by lepture** [comment]
@ashish-arora02 thanks

**Comment by sh4nks** [comment]
I am still getting this error. My code is identical to the one from "app.py" except that I am using Blueprints and the app factory for initializing it.
This is the code: https://gist.github.com/sh4nks/0f051d7e1089250ab943

**Comment by sh4nks** [comment]
Okay, this seems to be a problem on localhost/127.0.0.1.

I hope that I solved it now.
This way it worked: 
server accessed on localhost:8080
client accessed on 127.0.0.1:8000

redirect_uri is also 127.0.0.1:8000/authorized

I'll try it a few times and report back if that actually solved the problem (or if I was just lucky).

**Comment by vl4dt** [comment]
I hit this error too and eventually found that
```python
remote.authorized_response()
```
returns an instance of
```python
flask_oauthlib.client.OAuthException
```
that serializes to this string
```python
"Invalid response from remote"
```
the **tokensetter** is never called and the **token_handler** returns a **_401_** status code.

Added some extra logging to the code and this is the output:
```bash
INFO     2015-11-04 19:43:17,035 app.py:169] confirm: yes
INFO     2015-11-04 19:43:17,071 module.py:786] default: "POST /oauth/authorize HTTP/1.1" 302 -
INFO     2015-11-04 19:43:17,076 oauth2.py:491] uri, http_method, body, headers = http://127.0.0.1:8080/oauth/token, POST, {'grant_type': u'authorization_code', 'client_id': u'tQXdIG7IWZeqtTEpJbdPSEwrQiYn2GPvG1qXcVRO', 'client_secret': u'WvnfLoTOYgqnNAk47mrpaGMbXqhpoMeMwY4Hk20V2SWzS8vJh7', 'redirect_uri': u'http://localhost:9000/authorized', 'code': u'shJLp2J1B6ggpX9vHpn6aG1EVfDkWC'}, {'X-Appengine-Country': u'ZZ', 'Content-Length': u'237', 'Content-Type': u'application/x-www-form-urlencoded', 'User-Agent': u'Python-urllib/2.7', 'Host': u'127.0.0.1:8080'}
INFO     2015-11-04 19:43:17,076 oauth2.py:493] F: <function access_token at 0x7f780b00c320>
INFO     2015-11-04 19:43:17,077 oauth2.py:497] CREDENTIALS: {'version': '0.1.0'}
INFO     2015-11-04 19:43:17,084 oauth2.py:504] RET: ({u'Cache-Control': u'no-store', u'Content-Type': u'application/json', u'Pragma': u'no-cache'}, '{"error": "invalid_grant"}', 401)
INFO     2015-11-04 19:43:17,086 module.py:786] default: "POST /oauth/token HTTP/1.1" 401 26
```
I am still struggling with this and I'm not sure if I even have a clue as to what is really happening that causes this error.

**Comment by KleinYuan** [comment]
Cleaning up browser's cache/cookies/host data make it work for me, but just for once. Whenever I tried second time, it showed this.

**Comment by lepture** [comment]
the example is updated to [Authlib](https://authlib.org/)
